---
  - hosts: all
    become: yes
    vars:
      mysql_root_password: nothing
    tasks:
    - name: Install MySQL
      apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
      with_items:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev

    - name: Start the mysql service
      service:
        name: mysql
        state: started
        enabled: true

    - name: creating mysql user
      mysql_user:
         name: "{{db_user}}"
         password: "{{db_pass}}"
         priv: '*.*:ALL'
         host: '%'
         state: present

    - name: update mysql root password for all root accounts
      mysql_user:
        # login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: true
        login_user: root
        name: root
        priv: '*.*:ALL,GRANT'
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
      with_items:
        - 127.0.0.1
        - ::1
        - "localhost"

    - name: status check
      command: service mysql status
      register: status
      ignore_errors: yes

    - name: print status
      debug:
        msg: "mysql is {{ status.stdout }}"