---
- name: Deploy EC2 Instance
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create EC2 Instance
      ec2:
        key_name: tower
        region: us-east-1
        instance_type: t2.micro
        image: ami-053b0d53c279acc90
        access_key: "{{ my_access_key }}"
        secret_key: "{{ my_secret_key }}"
        # subnet_id: subnet-12345678
        group_id: sg-07951cffdd62f5a9b
        count: 1
        assign_public_ip: yes
        wait: true